# Register
POST http://localhost:5000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "username":"kalwabed",
    "email":"kaliwa@go.id",
    "password":"kalwabed"
}

# Login
POST http://localhost:5000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"kaliwa@go.id",
    "password":"kalwabed"
}

# Home
GET http://localhost:5000
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWQ3YmRmMWM5ZGU4ZjQyNTcxODIzNDMiLCJpYXQiOjE1OTEyMjg4MjJ9.NGEWDwxUca1au3OGez0yKDYZgy-c6ohEp15pmTsU9IA